config/routes.rb
Rails.application.routes.draw do

    root 'sales#index'
    get "pos" => "sales#pos", as: "pos"
    get 'fast_cash/index'
    get 'sales/product' => 'sales#product', as: 'product'
    get 'sales/order_item' =>  'sales#order_item', as: 'sales_order_item'
    get 'sales/send_to_order' => 'sales#send_to_order', as: 'send_to_order'
    get 'sales/send_to_printer' => 'sales#send_to_printer', as: 'send_to_printer'
    delete '/sales/order_item_destroy/:id' => 'sales#order_item_destroy', as: 'sales_order_item_destroy'
    post 'orders/order_customer' => 'orders#order_customer', as: 'order_customer'
    post 'fast_cash/set_cash' => 'fast_cash#set_cash', as: 'set_cash'
    post 'namual_cash/usd' => 'fast_cash#set_manual_cash_usd', as: 'set_manual_cash_usd'
    post 'namual_cash/riel' => 'fast_cash#set_manual_cash_riel', as: 'set_manual_cash_riel'
    get 'customers/populate/customer_name', to: 'customers#populate_customer_name', as: 'populate_customer_name'
    post 'payment/:id' => "tables#payment", as: "payment"
    get "print_reciept/:id" => "sales#print_reciept", as: "print_reciept"
    get "print_to_kitchen/:id" => "orders#print_to_kitchen", as: "print_to_kitchen"
    get 'print_success/:id' => "orders#print_success", as: "print_success"
    get "print_to_show/:id" => "orders#print_to_show", as: "print_to_show"
    get "edit_setting/:id" => "orders#edit_setting", as: "edit_setting"
    patch "update_for_setting/:id" => "orders#update_to_setting", as: "updated_setting"
    get "closed" => "order_items#closed", as: "closed"
    resources :deliveries
    resources :order_items
    resources :orders
    resources :customers
    resources :sales, only: [:index, :show]
    resources :cash_drawers
    
    devise_for :users, :controllers => { sessions: 'users/sessions' }
    devise_for :admins, :controllers => { :registrations => :registrations, sessions: 'admin/admins/sessions' }

    namespace :admin do
      get '/', to: 'dashboards#index', as: 'dashboards'
      resources :reports, only: [:index]
      resources :categories
      resources :products
      resources :cash_drawers
      resources :seat_tables
      resources :users
      resources :customers
      resources :reports, only: [:index]
      resources :exchange_rates
      resources :order_items
      resources :orders
      resources :admins
      resources :deliveries
      resources :exchange_rates
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :order_count
  before_action :set_locale

  # respond_to :html, :xml, :json, :js

  helper_method :current_order

  def current_order
    if !session["order_id#{current_user.id}"].nil?
      Order.find(session["order_id#{current_user.id}"])
    else
      Order.new(table_number: " Take Away #{SecureRandom.hex(8)}")
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name,:last_name, :gender, :birthdate, :role, :department, :photo, :pin, :is_pin_required,  :email,:password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :gender, :birthdate, :role, :department, :photo, :pin, :is_pin_required, :email,:password,:password_confirmation,:current_password])
  end

  def after_sign_out_path_for(resource_or_scope)
    session[:login_url] || request.referer || root_path
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  def store_current_location
    session['user_return_to'] = request.url
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      if admin_signed_in?
        admin_dashboards_path
      else
        root_path
      end
    else
      super
    end
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  def set_locale
    locale = I18n.available_locales.include?(params[:locale].to_sym) ? params[:locale] : I18n.locale if params[:locale].present?
    I18n.locale = locale || I18n.locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge(options)
  end

  def order_count
    @orders_count = Order.where('is_paid=? AND checkout_date=?', true, DateTime.now.to_date).order('id desc')

  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end
end

app/views/applications/_footer.html.erb
<!-- Footer -->
<footer class="footer pl-30 pr-30">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <p>2018 &copy; Codehub. Powered by Codehub</p>
      </div>
      <div class="col-sm-6 text-right">
        <p>Follow Us</p>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-google-plus"></i></a>
      </div>
    </div>
  </div>
</footer>
<!-- /Footer -->

app/views/applications/_nav.html.erb
<!-- Top Menu Items -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="nav-wrap">
    <div class="mobile-only-brand pull-left">
      <div class="nav-header pull-left">
        <div class="logo-wrap">
          <img class="brand-img" src="/mashisoyologo.png" alt="brand"/>
          <span class="brand-text"><img  src="/mashisoyologo.png" alt="brand"/></span>
        </div>
      </div>
      <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);">
        <i class="ti-align-left"></i>
      </a>
    </div>
    <div id="mobile_only_nav" class="mobile-only-nav pull-right">
      <ul class="nav navbar-right top-nav pull-right">
        <li class="dropdown auth-drp">
          <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown">
          <%if current_user.image.present?%>
            <img src="<%=current_user.image.url%>" alt="user_auth" class="user-auth-img img-circle" /><span class="user-online-status"></span></a>
          <%else%>
            <img src="/profile.png" alt="user_auth" class="user-auth-img img-circle" /><span class="user-online-status"></span></a>
          <%end%>
          <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
            <li class="divider"></li>
            <li>
              <%=link_to destroy_user_session_path, method: :delete do%>
              <i class="zmdi zmdi-power"></i><span>Log Out</span>
              <%end%>
            </li>
          </ul>
        </li>
        <li>
        <% if I18n.locale == :km %>
          <%= link_to url_for(params.permit(:locale).merge({locale: 'en'})), data: { turbolinks: false } do %>
            <img src="en.svg" width="40"> 
          <%end%>
        <% else %>
          <%= link_to url_for(params.permit(:locale).merge({locale: 'km'})), data: { turbolinks: false } do %>
            <img src="km.svg" width="40">
          <%end%>
        <% end %>
      </li>
      </ul>
    </div>
  </div>
</nav>
<!-- /Top Menu Items -->

<!-- Left Sidebar Menu -->
<div class="fixed-sidebar-left">
  <ul class="nav navbar-nav side-nav nicescroll-bar">
    <li class="navigation-header">
      <span>Main</span>
      <hr />
    </li>
    <li>
      <%=link_to sales_path do%>
        <div class="pull-left">
          <i class="ti-dashboard mr-20"></i>
          <span class="right-nav-text"><%=t('.sales')%></span></div>
        <div class="clearfix"></div>
      <%end%>
    </li>
    <li>
      <%=link_to customers_path do%>
        <div class="pull-left">
          <i class="ti-user mr-20"></i>
          <span class="right-nav-text"><%=t('.customers')%></span></div>
        <div class="clearfix"></div>
      <%end%>
    </li>
    <li>
      <%=link_to orders_path(state: "ordered") do%>
        <div class="pull-left">
          <i class=" ti-receipt mr-20"></i>
          <span class="right-nav-text session_order_count">
            <%=t('.orders')%> (<%= "#{ Order.where("is_paid=? AND order_status=? AND order_date=?", false, "order",DateTime.now.to_date).count}" %>)
          </span>
        </div>
        <div class="clearfix"></div>
      <%end%>
    </li>
    <li>
      <%=link_to orders_path(state: "completed") do%>
        <div class="pull-left">
          <i class="ti-clipboard mr-20"></i>
          <span class="right-nav-text">
            <%=t('.invoices')%> (<%= "#{ Order.where('is_paid=? AND order_status=? AND order_date=?', true, "completed",DateTime.now.to_date).count}" %>)
          </span>
        </div>
        <div class="clearfix"></div>
      <%end%>
    </li>
    <li>
      <%=link_to cash_drawers_path do%>
        <div class="pull-left">
          <i class="ti-key mr-20"></i>
          <span class="right-nav-text">
            <%=t('.Cash Drawer')%>
          </span>
        </div>
        <div class="clearfix"></div>
      <%end%>
    </li>
    <%if current_user.role == "admin"%>
      <li>
        <%=link_to order_items_path do%>
          <div class="pull-left"><i class="ti-money mr-20"></i><span class="right-nav-text"><%= @orders_count.count > 0 ? "Sales (#{@orders_count.count})" : "Sales"%></span></div>
          <div class="clearfix"></div>
        <%end%>
      </li>
    <%else%>
      <li>
        <%=link_to order_items_path do%>
          <div class="pull-left"><i class="ti-money mr-20"></i><span class="right-nav-text"><%= session[:order_count].present? ? "Sales (#{session[:sale_count]})" : "Sales"%></span></div>
          <div class="clearfix"></div>
        <%end%>
      </li>
    <%end%>


  </ul>
</div>
<!-- /Left Sidebar Menu -->