config/routes.rb
Rails.application.routes.draw do

    root 'sales#index'
    get "pos" => "sales#pos", as: "pos"
    get 'fast_cash/index'
    get 'sales/product' => 'sales#product', as: 'product'
    get 'sales/order_item' =>  'sales#order_item', as: 'sales_order_item'
    get 'sales/send_to_order' => 'sales#send_to_order', as: 'send_to_order'
    get 'sales/send_to_printer' => 'sales#send_to_printer', as: 'send_to_printer'
    delete '/sales/order_item_destroy/:id' => 'sales#order_item_destroy', as: 'sales_order_item_destroy'
    post 'orders/order_customer' => 'orders#order_customer', as: 'order_customer'
    post 'fast_cash/set_cash' => 'fast_cash#set_cash', as: 'set_cash'
    post 'namual_cash/usd' => 'fast_cash#set_manual_cash_usd', as: 'set_manual_cash_usd'
    post 'namual_cash/riel' => 'fast_cash#set_manual_cash_riel', as: 'set_manual_cash_riel'
    get 'customers/populate/customer_name', to: 'customers#populate_customer_name', as: 'populate_customer_name'
    post 'payment/:id' => "tables#payment", as: "payment"
    get "print_reciept/:id" => "sales#print_reciept", as: "print_reciept"
    get "print_to_kitchen/:id" => "orders#print_to_kitchen", as: "print_to_kitchen"
    get 'print_success/:id' => "orders#print_success", as: "print_success"
    get "print_to_show/:id" => "orders#print_to_show", as: "print_to_show"
    get "edit_setting/:id" => "orders#edit_setting", as: "edit_setting"
    patch "update_for_setting/:id" => "orders#update_to_setting", as: "updated_setting"
    get "closed" => "order_items#closed", as: "closed"
    resources :deliveries
    resources :order_items
    resources :orders
    resources :customers
    resources :sales, only: [:index, :show]
    resources :cash_drawers
    
    devise_for :users, :controllers => { sessions: 'users/sessions' }
    devise_for :admins, :controllers => { :registrations => :registrations, sessions: 'admin/admins/sessions' }

    namespace :admin do
      get '/', to: 'dashboards#index', as: 'dashboards'
      resources :reports, only: [:index]
      resources :categories
      resources :products
      resources :cash_drawers
      resources :seat_tables
      resources :users
      resources :customers
      resources :reports, only: [:index]
      resources :exchange_rates
      resources :order_items
      resources :orders
      resources :admins
      resources :deliveries
      resources :exchange_rates
    end

end

app/models/order.rb
class Order < ApplicationRecord

  OPTION_TABLE = [
    "Take Away",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "9",
    "10"
  ]

  belongs_to :user
  belongs_to :admin, optional: true

  belongs_to :customer

  belongs_to :seat_table, optional: true

  has_many :invoices

  has_many :order_items, dependent: :destroy
  
  belongs_to :delivery, optional: true

  scope :unpaid_order, -> { where(is_paid: false) }

  scope :paid_order, -> { where(is_paid: true) }

  before_save :update_subtotal

  before_update :update_chash_in

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) * (1 - oi.discount / 100) : 0 }.sum
  end

  def cost
    order_items.collect { |oi| oi.valid? ? (oi.product.original_price * oi.quantity) : 0 }.sum
  end

  def total
    subtotal + (subtotal * self[:tax] / 100) - (subtotal * (self[:discount] / 100))
  end

  private
    def update_subtotal
      self[:subtotal] = subtotal
      self[:total] = subtotal + (subtotal * self[:tax] / 100) - (subtotal * (self[:discount] / 100))
      delivery_fe = delivery.present? ?  delivery.delivery_fee : 0
      self[:delivery_fee] = subtotal * (delivery_fe.to_d / 100)
      total_minius_tax = (total - (subtotal * self[:tax] / 100))
      profit = total_minius_tax - cost - delivery_fee
      puts "Subtotal: #{subtotal}"
      puts "Total: #{total}"
      puts "delivery fee: #{delivery_fee}"
      puts "discount: #{(subtotal * (self[:discount] / 100))}"
      puts "Tax: #{(subtotal * self[:tax] / 100)}"
      puts "Grand Total: #{total - delivery_fee}"
      self[:profit] = profit
      puts "profit: #{profit}"
    end

    def update_chash_in
      self[:total_cash_in_riel] = self[:cash] * Constant::exchange_rate + self[:cash_in_riel]
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < DashboardsController
  
  before_action :authenticate_admin!
  layout "dashboards"
  def index
    @orders = Order.where(is_paid: true).order(created_at: :desc).limit(30)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new

  end

  def create
    @order = current_admin.orders.build(order_params)
    if @order.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to orders_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or order Duplicated"
        format.html { redirect_to orders_path }
        format.js { render template: "/orders/order_error.js.erb" }
      end
    end
  end

  def edit
    @order = Order.find(params[:id])
    session[:redirect] = params[:redirect]
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to order_path(@order), notice: "Successful Updated"
    else
      render :edit
    end
  end

  def destroy
    @order = Order.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to orders_url }
      format.js
    end
  end

  private
    def order_params
      params.required(:order).permit!
    end
end

app/controllers/orders_controller.rb
class OrdersController < DashboardsController
  before_action :authenticate_user!
  def index
    # if params[:query].present?
    #   @orders = Order.unpaid_order.search(params[:query])
    # else
    #   @orders = Order.where('is_paid=? AND order_status=?', false, "order").order('id desc')
    # end 
    if params[:state] == "ordered"
      @orders = Order.where('is_paid=? AND order_status=? AND order_date =?', false, "order", DateTime.now.to_date).order('created_at desc')
    else
      @orders = Order.where('is_paid=? AND order_status=? AND order_date = ?', true, "completed", DateTime.now.to_date).order('created_at desc')
    end
  end

  def show
    @orders_count = Order.where('is_paid=? AND checkout_date=?', true, DateTime.now.to_date).order('id desc')
    @order = Order.find(params[:id])
    @order_items = Order.unpaid_order.find(session["order_id#{current_user.id}"]).order_items if session["order_id#{current_user.id}"].present?
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
    session[:redirect] = params[:redirect]
  end

  def edit_setting 
    @order_setting = Order.find(params[:id])
    session[:redirect] = params[:redirect]
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)      
      if session[:redirect].present?
        redirect_to order_path(@order)
      else
        redirect_to orders_path, notice: "Your order has been updated."
      end
      session.delete(:redirect)
    else 
      puts @order.errors.full_messages
      render :edit, notice: "Something went wrong."
    end
  end

  def update_to_setting
    @order = Order.find(params[:id])

    if @order.update(order_params)      
      if session[:redirect].present?
        flash[:notice] = "Update Successfully"
        redirect_to sales_path
      else
        redirect_to orders_path, notice: "Your order has been updated."
      end
      session.delete(:redirect)
    else 
      puts @order.errors.full_messages
      render :edit, notice: "Something went wrong."
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      respond_to do |format|
        flash.now[:alert] = "Table #{@order.table_number} Has Been Removed!"
        format.html { redirect_to orders_path  }
        format.js
      end
      session.delete("order_id#{current_user.id}")
    end
  end

  
  def print_to_kitchen
    @order = Order.find(params[:id])
  end

  def update_print_status
    @order = Order.find(params[:id])

  end

  def print_to_show
    @order = Order.find(params[:id])

  end

  def print_success
    redirect_to sales_path
    flash[:notice] = "Print To Kitchen Successfully"
  end

  private
    def order_params
      params.required(:order).permit!
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/destroy.js.erb
$('.delete_order_<%=@order.id%>').remove();

app/views/admin/orders/edit.html.erb
<!-- Main Content -->
<div class="page-wrapper">
  <div class="container pt-30">
    <div class="row">
      <div class="col-md-9">
        <div class="panel panel-success card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-light">Edit Product</h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <%= simple_form_for([:admin, @order]) do |f| %>
              <% if @order.errors.any? %>
              <div id="error_explanation">
                <h4>
                  <%= pluralize(@order.errors.count, "error") %>
                  prohibited this cash drawer from being saved:
                </h4>
                <ul>
                  <% @order.errors.full_messages.each do |message| %>
                    <li>
                      <%= message %>
                    </li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="row">

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Order Name</label>
                    <%= f.text_field :order_name, class: "form-control" %>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Order Date</label>
                    <%= f.text_field :order_date, :class => 'form-control', placeholder: "Choose order date", disabled: true %>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Order Time</label>
                    <%= f.text_field :order_time, :as => :string, :value => time_format(f.object.order_time), :class => 'form-control', label: false, placeholder: "Choose order time", disabled: true %>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Tax</label>
                    <%=f.number_field :tax, class: "form-control"%>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Shipping</label>
                    <%=f.number_field :shipping, class: "form-control"%>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Discount</label>
                    <%=f.number_field :discount, class: "form-control"%>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Customer</label>
                    <%=f.collection_select :customer_id, Customer.all, :id, :customer_name, { prompt: "Select Customer" } , {class: "form-control select2"}%>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label mb-10">Table</label>
                    <%=f.collection_select :seat_table_id, SeatTable.all, :id, :table_number, { prompt: "Select Table" } , {class: "form-control select2"}%>
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="modal-footer">
                    <%=link_to "Cancle", sales_path, class: "btn btn-default"%>
                    <%=f.submit class: "btn btn-success"%>
                  </div>
                </div>
              </div>

            <%end%>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%=render "applications/footer"%>

</div>
<!-- /Main Content -->

app/views/admin/orders/index.html.erb
<div class="wrapper theme-2-active navbar-top-light horizontal-nav">
  <%=render "components/nav"%>
  <%=render "components/setting"%>
  <!-- Main Content -->
  <div class="page-wrapper">
    <div class="container pt-30">
      <!-- Row -->
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default border-panel card-view">
            <div class="panel-heading">
              <div class="pull-left">
                <h6 class="panel-title txt-dark">order</h6>
              </div>
              <div class="clearfix"></div>
            </div>
            <div class="panel-wrapper collapse in">
              <div class="panel-body">
                <div class="table-wrap">
                  <div class="">
                    <table id="example" class="cell-border">
                      <thead>
                        <tr>
                          <th>Invoice No</th>
                          <th>Order Date</th>
                          <th>Order Time</th>
                          <th>Customer</th>
                          <th>Order Tax</th>
                          <th>Order Shipping</th>
                          <th>Subtotal</th>
                          <th>Discount</th>
                          <th>Grand Total</th>
                          <th>Profit</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        <%@orders.each do |order|%>
                        <tr class="delete_order_<%=order.id%>">
                          <td>
                            <%= '%05d' % order.id %>
                          </td>
                          <td>
                            <%= order.order_date.strftime("%B %d, %Y") %>
                          </td>
                          <td>
                            <%= order.order_time.strftime("%I:%M %p") %>
                          </td>
                          <td>
                            <%= order.customer.customer_name %>
                          </td>
                          <td>
                            <%= order.tax %>
                          </td>
                          <td>
                            <%= order.shipping %>
                          </td>
                          <td>
                            <%= number_to_currency(order.subtotal, precision: 2) %>
                          </td>
                          <td>
                            <%= number_to_percentage(order.discount, precision: 0) %>
                          </td>
                          <td>
                            <%= number_to_currency(order.total, precision: 2) %>
                          </td>
                          <td>
                            <%= number_to_currency(order.profit, precision: 2) %>
                          </td>
                          <td>
                            <%=link_to admin_order_path(order),class: "btn btn-primary", email: "View" do %>
                            View
                            <%end%>
                            <%=link_to edit_admin_order_path(order),class: "btn btn-primary", email: "Edit",id: "show-form_#{order.id}" do %>
                            Edit
                            <%end%>
                          </td>
                        </tr>
                        <%end%>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /Row -->
    </div>

    <%=render "components/footer"%>

  </div>
  <!-- /Main Content -->
</div>

app/views/admin/orders/show.html.erb
<!-- Main Content -->
<div class="page-wrapper">
  <div class="container" style="margin-top: 20px;">
    <!-- Row -->
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default border-panel card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark">Invoice</h6>
            </div>
            <div class="pull-right">
              <h6 class="txt-dark">Order #000<%=@order.id%></h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">

              <div class="row">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-6 text-right">
                  <address>
                    <span class="txt-dark head-font capitalize-font mb-5">order date:</span><br>
                    <%=@order.order_date.strftime("%B %d, %Y")%><br><br>
                    <span class="txt-dark head-font capitalize-font mb-5">Discount: </span><br>
                    <%=number_to_percentage(@order.discount, precision: 0)%><br><br>
                    <span class="txt-dark head-font capitalize-font mb-5">Profit: </span><br>
                    <%=number_to_currency(@order.profit, precision: 2)%><br><br>
                  </address>
                </div>
              </div>

              <div class="seprator-block"></div>

              <div class="invoice-bill-table">
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Item</th>
                        <th>Sell Price</th>
                        <th>Original Price</th>
                        <th>Quantity</th>
                        <th>Discount Per / Item</th>                      
                        <th>Totals</th>
                        <th>Profit</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%@order.order_items.each do |item|%>
                        <tr>
                          <td><%=item.product.product_name.capitalize%></td>
                          <td><%=number_to_currency(item.product.product_price)%></td>
                          <td><%=number_to_currency(item.product.original_price)%></td>
                          <td><%=item.quantity%></td>
                          <td><%=number_to_percentage(item.discount, precision: 0)%></td>
                          <td><%=number_to_currency(item.total_price)%></td>
                          <td><%=number_to_currency((item.product.product_price - item.product.original_price) * item.quantity) %></td>
                        </tr>
                      <%end%>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Total</td>
                        <td>Profit</td>
                      </tr>
                      <tr class="txt-dark">
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><%=number_to_currency(@order.total)%></td>
                        <td><%=number_to_currency(@order.profit)%></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="button-list pull-right">
                  <%=link_to "Cancel", admin_orders_path, class: "btn btn-orange mr-10", id: "cancel"%>
                  <button id="print" type="button" class="btn btn-default btn-outline btn-icon left-icon" onclick="javascript:window.print();">
                    <i class="fa fa-print"></i>
                    <span>
                      Print</span>
                  </button>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Row -->
    <%=render "applications/footer"%>
  </div>

<script>

  jQuery("#checkout").on('click', function() {
    $('div#cont').removeClass('container');
    $('div#card').removeClass('card-panel');
    print();
  });

</script>