config/routes.rb
Rails.application.routes.draw do

    root 'sales#index'
    get "pos" => "sales#pos", as: "pos"
    get 'fast_cash/index'
    get 'sales/product' => 'sales#product', as: 'product'
    get 'sales/order_item' =>  'sales#order_item', as: 'sales_order_item'
    get 'sales/send_to_order' => 'sales#send_to_order', as: 'send_to_order'
    get 'sales/send_to_printer' => 'sales#send_to_printer', as: 'send_to_printer'
    delete '/sales/order_item_destroy/:id' => 'sales#order_item_destroy', as: 'sales_order_item_destroy'
    post 'orders/order_customer' => 'orders#order_customer', as: 'order_customer'
    post 'fast_cash/set_cash' => 'fast_cash#set_cash', as: 'set_cash'
    post 'namual_cash/usd' => 'fast_cash#set_manual_cash_usd', as: 'set_manual_cash_usd'
    post 'namual_cash/riel' => 'fast_cash#set_manual_cash_riel', as: 'set_manual_cash_riel'
    get 'customers/populate/customer_name', to: 'customers#populate_customer_name', as: 'populate_customer_name'
    post 'payment/:id' => "tables#payment", as: "payment"
    get "print_reciept/:id" => "sales#print_reciept", as: "print_reciept"
    get "print_to_kitchen/:id" => "orders#print_to_kitchen", as: "print_to_kitchen"
    get 'print_success/:id' => "orders#print_success", as: "print_success"
    get "print_to_show/:id" => "orders#print_to_show", as: "print_to_show"
    get "edit_setting/:id" => "orders#edit_setting", as: "edit_setting"
    patch "update_for_setting/:id" => "orders#update_to_setting", as: "updated_setting"
    get "closed" => "order_items#closed", as: "closed"
    resources :deliveries
    resources :order_items
    resources :orders
    resources :customers
    resources :sales, only: [:index, :show]
    resources :cash_drawers
    
    devise_for :users, :controllers => { sessions: 'users/sessions' }
    devise_for :admins, :controllers => { :registrations => :registrations, sessions: 'admin/admins/sessions' }

    namespace :admin do
      get '/', to: 'dashboards#index', as: 'dashboards'
      resources :reports, only: [:index]
      resources :categories
      resources :products
      resources :cash_drawers
      resources :seat_tables
      resources :users
      resources :customers
      resources :reports, only: [:index]
      resources :exchange_rates
      resources :order_items
      resources :orders
      resources :admins
      resources :deliveries
      resources :exchange_rates
    end

end

app/views/admin/admins/_admin.html.erb
<tr class="delete_admin_<%=admin.id%>">
  <td>
    <%=admin.username%>
  </td>
  <td>
    <%=admin.email%>
  </td>
  <td>
    <%=time_ago(admin.created_at)%>
  </td>
  <td>
    <%=form_for([:admin, admin], remote: true) do |f|%>
      <%=link_to admin_admin_path(admin),class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
        View
      <%end%>
      <%=link_to edit_admin_admin_path(admin),id: "link_#{admin.id}",class: "btn btn-primary" do %>
        Edit
      <% end %>
    <%end%>
  </td>
</tr>

app/views/admin/admins/_admin_form.html.erb
<%=simple_form_for([:admin, admin], remote: true) do |f|%>
  <div class="row">
    <div class="col-lg-12">
      <h2>Administrator Security</h2>
    </div>
   <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Username</label>
        <%=f.text_field :username, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Email</label>
        <%=f.text_field :email, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Password</label>
        <%=f.password_field :password, class: "form-control"%>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Confirmation Password</label>
        <%=f.password_field :password_confirmation, class: "form-control"%>
      </div>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-lg-12">
      <h2>Administrator Information</h2>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Role</label>
        <%=f.select :role,(Admin.roles.keys.map{ |role| [role.titleize, role]}), {}, {:class=>"form-control"}%>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">First Name</label>
        <%=f.text_field :first_name, class: "form-control"%>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label for="recipient-name" class="control-label mb-10">Last Name</label>
        <%=f.text_field :last_name, class: "form-control"%>
      </div>
    </div>
    <div class="col-md-12">
      <div class="control-group file-upload" id="file-upload1">
      <h3>Upload Photo</h3>
      <div class="image-box text-center"><p>Upload Image</p><img src="" alt=""></div>
        <div class="controls">
            <%=f.file_field :image%>
        </div>
      </div>
    </div>
    
    <div class="col-md-12">
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%=f.submit class: "btn btn-success"%>
      </div>
    </div>
  </div>

<%end%>

app/views/admin/admins/admin_error.js.erb
$("input#admin_email").val("");
$("input#admin_fullname").val("");
$("input#admin_organization").val("");
$("#admin-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/admins/admin_success.js.erb
$("input#admin_email").val("");
$("input#admin_fullname").val("");
$("input#admin_organization").val("");
$("#admin-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/admins/edit.html.erb
<div class="wrapper theme-2-active navbar-top-light horizontal-nav">
	<%=render "components/nav"%>
	<%=render "components/setting"%>
	<!-- Main Content -->
	<div class="page-wrapper">
		<div class="container pt-30">
			<div class="row">
				<div class="col-md-9">
					<div class="panel panel-success card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-light">Edit Product</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">                         
                <%=simple_form_for([:admin, @admin]) do |f|%>
                  <div class="row">
                    <div class="col-lg-12">
                      <h2>Administrator Security</h2>
                    </div>
                  <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Username</label>
                        <%=f.text_field :username, class: "form-control"%>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Email</label>
                        <%=f.text_field :email, class: "form-control"%>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Password</label>
                        <%=f.password_field :password, class: "form-control"%>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Confirmation Password</label>
                        <%=f.password_field :password_confirmation, class: "form-control"%>
                      </div>
                    </div>
                  </div>
                  <hr/>
                  <div class="row">
                    <div class="col-lg-12">
                      <h2>Administrator Information</h2>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Role</label>
                        <%=f.select :role,(Admin.roles.keys.map{ |role| [role.titleize, role]}), {}, {:class=>"form-control"}%>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">First Name</label>
                        <%=f.text_field :first_name, class: "form-control"%>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Last Name</label>
                        <%=f.text_field :last_name, class: "form-control"%>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="recipient-name" class="control-label mb-10">Discountinue</label>
                        <br>
                        <%=f.check_box :is_active%>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="control-group file-upload" id="file-upload1">
                        <h3>Upload Photo</h3>
                        <%if @admin.image.present?%>
                          <img class="image-box" src="<%=@admin.image.url%>" alt="">
                        <%else%>
                          <div class="image-box text-center"><p>Upload Image</p><img src="" alt=""></div>
                        <%end%>
                        <div class="controls">
                            <%=f.file_field :image%>
                        </div>
                      </div>
                    </div>
                    
                    <div class="col-md-12">
                      <div class="modal-footer">
                        <%=link_to "Cancel", admin_admins_path, class: "btn btn-default"%>
                        <%=f.submit class: "btn btn-success"%>
                      </div>
                    </div>
                  </div>

                <%end%>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<%=render "components/footer"%>

</div>
<!-- /Main Content -->
</div>

app/views/admin/admins/index.html.erb
<div class="wrapper theme-2-active navbar-top-light horizontal-nav">
	<%=render "components/nav"%>
	<%=render "components/setting"%>
	<!-- Main Content -->
	<div class="page-wrapper">
		<div class="container pt-30">
			<!-- Title -->
			<div class="row heading-bg">
				<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
					<h5 class="txt-dark">Administrator</h5>
					<div class="panel-wrapper collapse in">
						<div class="panel-body" style="padding-left: 0px;">
							<div class="button-list">
								<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Add New</button>
							</div>
							<div class="modal fade bs-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
								<div class="modal-dialog modal-lg" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span></button>
											<h5 class="modal-title" id="exampleModalLabel1">New Administrator</h5>
										</div>
										<div class="modal-body">
											<div id="admins">
												<div id="admin-errors"></div>
												<div id="admin-success"></div>
												<%=render partial: "admin_form", locals: {admin: @admin}%>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Breadcrumb -->
				<div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
					<ol class="breadcrumb">
						<li>
							<a href="/admin/dashboard">Dashboard</a>
						</li>
						<li class="active">
							<span>Administrator</span></li>
					</ol>
				</div>
				<!-- /Breadcrumb -->
			</div>
			<!-- /Title -->

			<!-- Row -->
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default border-panel card-view">
						<div class="panel-heading">
							<div class="pull-left">
								<h6 class="panel-title txt-dark">Administrator</h6>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="panel-wrapper collapse in">
							<div class="panel-body">
								<div class="table-wrap">
									<div class="">
										<table id="example" class="table table-hover display  pb-30">
											<thead>
												<tr>
													<th>Username</th>
													<th>Email</th>
													<th>Created At</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody id="admin-index">
												<%if @admins.any?%>
													<%= render @admins%>
												<%end%>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Row -->
		</div>

		<%=render "components/footer"%>

	</div>
	<!-- /Main Content -->
</div>

app/views/admin/admins/show.html.erb
<div class="wrapper theme-2-active navbar-top-light horizontal-nav">
  <%=render "components/nav"%>
  <%=render "components/setting"%>
  <!-- Main Content -->
  <div class="page-wrapper">
    <div class="container pt-30">
      <div class="col-sm-4">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default card-view  pa-0">
              <div class="panel-wrapper collapse in">
                <div class="panel-body  pa-0">
                  <div class="profile-box">
                    <div class="profile-cover-pic">
                      <div class="fileupload btn btn-default">
                        <%=link_to edit_admin_admin_path(current_admin.id) do%>
                        <span class="btn-text">edit</span>
                        <%end%>
                      </div>
                      <div class="profile-image-overlay"></div>
                    </div>
                    <div class="profile-info text-center mb-15">
                      <div class="profile-img-wrap">
                        <%if current_admin.image.present?%>
                        <img class="inline-block mb-10" src="<%=current_admin.image.url%>" alt="user">
                        <%else%>
                        <img class="inline-block mb-10" src="/no-image.png" alt="user">
                        <%end%>
                        <div class="fileupload btn btn-default">
                          <%=link_to edit_admin_admin_path(current_admin.id) do%>
                          <span class="btn-text">edit</span>
                          <%end%>
                        </div>
                      </div>
                      <h5 class="block mt-10 weight-500 capitalize-font txt-dark"><%=current_admin.username.capitalize%>
                      </h5>
                      <h6 class="block capitalize-font"><%=current_admin.role%></h6>
                    </div>
                    <div class="social-info">
                      <%=link_to edit_admin_admin_path(current_admin.id), class: "btn btn-orange btn-block  btn-anim mt-15" do%>
                      <i class="fa fa-pencil"></i><span class="btn-text">edit profile</span>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-8">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default card-view pa-0">
              <div class="panel-wrapper collapse in">
                <div class="panel-body pb-0">
                  <div class="tab-struct custom-tab-1">
                    <ul role="tablist" class="nav nav-tabs nav-tabs-responsive" id="myTabs_8">
                      <li class="active" role="presentation"><a data-toggle="tab" id="profile_tab_8" role="tab"
                          href="#profile_8" aria-expanded="false"><span>profile</span></a></li>
                    </ul>
                    <div class="tab-content" id="myTabContent_8">
                      <div id="profile_8" class="tab-pane fade active in" role="tabpanel">
                        <div class="col-md-12">
                          <div class="pt-20">
                            <div class="streamline user-activity">

                              <div class="sl-item">
                                <a href="javascript:void(0)">
                                  <div class="sl-avatar avatar avatar-sm avatar-circle">
                                    <%if current_admin.photo.present?%>
                                    <img class="img-responsive img-circle" src="<%=current_admin.photo%>" alt="avatar">
                                    <%else%>
                                    <img class="img-responsive img-circle" src="/no-image.png" alt="avatar">
                                    <%end%>
                                  </div>
                                  <div class="sl-content">
                                    <p class="inline-block">Fullname: <span
                                        class="capitalize-font txt-orange mr-5 weight-500"><%= "#{current_admin.first_name}" + "#{current_admin.last_name}"%></span>
                                    </p>
                                    <br />
                                    <p class="inline-block">Username: <span
                                        class="capitalize-font txt-orange mr-5 weight-500"><%=current_admin.username%></span>
                                    </p>
                                    <span class="block txt-grey font-12 capitalize-font">Created_at:
                                      <%=time_ago(current_admin.created_at)%></span>
                                    <span class="block txt-grey font-12 capitalize-font">Role:
                                      <%=current_admin.role%></span>
                                  </div>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%=render "components/footer"%>

</div>
<!-- /Main Content -->
</div>