config/routes.rb
Rails.application.routes.draw do

    root 'sales#index'
    get "pos" => "sales#pos", as: "pos"
    get 'fast_cash/index'
    get 'sales/product' => 'sales#product', as: 'product'
    get 'sales/order_item' =>  'sales#order_item', as: 'sales_order_item'
    get 'sales/send_to_order' => 'sales#send_to_order', as: 'send_to_order'
    get 'sales/send_to_printer' => 'sales#send_to_printer', as: 'send_to_printer'
    delete '/sales/order_item_destroy/:id' => 'sales#order_item_destroy', as: 'sales_order_item_destroy'
    post 'orders/order_customer' => 'orders#order_customer', as: 'order_customer'
    post 'fast_cash/set_cash' => 'fast_cash#set_cash', as: 'set_cash'
    post 'namual_cash/usd' => 'fast_cash#set_manual_cash_usd', as: 'set_manual_cash_usd'
    post 'namual_cash/riel' => 'fast_cash#set_manual_cash_riel', as: 'set_manual_cash_riel'
    get 'customers/populate/customer_name', to: 'customers#populate_customer_name', as: 'populate_customer_name'
    post 'payment/:id' => "tables#payment", as: "payment"
    get "print_reciept/:id" => "sales#print_reciept", as: "print_reciept"
    get "print_to_kitchen/:id" => "orders#print_to_kitchen", as: "print_to_kitchen"
    get 'print_success/:id' => "orders#print_success", as: "print_success"
    get "print_to_show/:id" => "orders#print_to_show", as: "print_to_show"
    get "edit_setting/:id" => "orders#edit_setting", as: "edit_setting"
    patch "update_for_setting/:id" => "orders#update_to_setting", as: "updated_setting"
    get "closed" => "order_items#closed", as: "closed"
    resources :deliveries
    resources :order_items
    resources :orders
    resources :customers
    resources :sales, only: [:index, :show]
    resources :cash_drawers
    
    devise_for :users, :controllers => { sessions: 'users/sessions' }
    devise_for :admins, :controllers => { :registrations => :registrations, sessions: 'admin/admins/sessions' }

    namespace :admin do
      get '/', to: 'dashboards#index', as: 'dashboards'
      resources :reports, only: [:index]
      resources :categories
      resources :products
      resources :cash_drawers
      resources :seat_tables
      resources :users
      resources :customers
      resources :reports, only: [:index]
      resources :exchange_rates
      resources :order_items
      resources :orders
      resources :admins
      resources :deliveries
      resources :exchange_rates
    end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :authenticate_user!

  def pos
    if params[:action] === "pos"
      session.delete("order_id#{current_user.id}")
    end
    redirect_to sales_path
  end

  def index
    @categories = Category.order(id: :asc)
    session[:order_count] = current_user.orders.where('is_paid=? AND order_date=? AND order_status=?', false, DateTime.now.to_date, 'order').count
    session[:sale_count] = current_user.orders.where('is_paid=? AND order_date=?', true, DateTime.now.to_date).count

    if params[:order_id].present?
       session["order_id#{current_user.id}"] = params[:order_id]
       @order_items = Order.unpaid_order.find(params[:order_id]).order_items
    end

    if params[:customer_id].present?
      current_order.update(customer_id: params[:customer_id])
      session["customer_id#{current_user.id}"] = params[:customer_id]
    end

    @order_items = Order.unpaid_order.find(session["order_id#{current_user.id}"]).order_items if session["order_id#{current_user.id}"].present?
    @products = Category.find(session["category_id#{current_user.id}"]).products.where(status: true).order('product_name') if session["category_id#{current_user.id}"].present?
  end

  def product
    @products = Category.find(params[:category_id]).products.where(status: true).order('product_name')
    session["category_id#{current_user.id}"] = params[:category_id] if params[:category_id].present?
  end

  def order_item
    @order = current_order
    @order.order_date = DateTime.now.to_date
    puts "Time: #{Time.zone.now.strftime("%I:%M %p")}"
    @order.order_time = Time.zone.now.strftime("%I:%M %p")
    @order.waitting_no = Order.where(order_date: DateTime.now.to_date).order('id').pluck(:waitting_no).last.to_i + 1 if @order.waitting_no.nil?
    @order.user_id = current_user.id
    @order.tax = Constant::vat
    if session["customer_id#{current_user.id}"].present?
       @order.customer_id = session["customer_id#{current_user.id}"]
    else
      @order.customer_id = 1
    end

    if !(order_item = check_exist(@order, params[:product_id].to_i)).nil?
      order_item.update(quantity: order_item.quantity + 1)
    else
      @order_item = @order.order_items.new
      @order_item.product_id = params[:product_id]
      @order_item.quantity = params[:quantity]
      @order_item.save
      puts "Show"
    end

    if @order.save
      session["order_id#{current_user.id}"] = @order.id
      @order_items = Order.find(session["order_id#{current_user.id}"]).order_items
      puts "Show Not"
    end
  end

  def check_exist(order, product_id)
    order.order_items.each do |order_item|
      if product_id == order_item.product_id
        return order_item
      end
    end
    return nil
  end

  def send_to_order
    if session["order_id#{current_user.id}"].present?
      @order = Order.find(session["order_id#{current_user.id}"])
      @order.order_status = 'order'
      if session["customer_id#{current_user.id}"].present?
        @order.customer_id = session["customer_id#{current_user.id}"]
      end
      @order.save
      session.delete("order_id#{current_user.id}")
      session.delete("customer_id#{current_user.id}")
      @order_items = @order.order_items
      session[:order_count] = current_user.orders.where('is_paid=? AND order_date=? AND order_status=?', false, DateTime.now.to_date, 'order').count
      respond_to do |format|
        flash.now[:notice] = "Save Successfully"
        format.js { render :order_item }
      end
    end
  end

  def order_item_destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
    if @order_items.count == 0
      session.delete("order_id#{current_user.id}")
    end
    respond_to do |format|
      format.js { render :order_item }
    end
  end

  def send_to_printer
    @order = current_order
    if @order.update(is_paid: true)
      @order_items = @order.order_items
      session.delete("order_id#{current_user.id}")
      session.delete("customer_id#{current_user.id}")
      respond_to do |format|
        format.json {
          render json: @order_items
        }
      end
    end
  end

  def show
    @order = Order.find(params[:id])
    redirect_to order_path(@order, state: "reciept")
  end

  def print_reciept
    @order = Order.find(params[:id])
    if @order.update(
        is_paid: true, 
        user_id: current_user.id, 
        checkout_date: Date.today, 
        checkout_time: Time.zone.now.strftime("%I:%M %p"),
        table_number: "Take Away #{SecureRandom.hex(8)}",
        real_table_number: @order.table_number,
        order_status: "completed",
        delivery_fee: @order.delivery.present? ? @order.delivery.delivery_fee : 0,
      )
      redirect_to sales_path
    end
    session.delete("order_id#{current_user.id}")
    session.delete("customer_id#{current_user.id}")
  end

end

app/views/sales/_order_item_row.html.erb
<% if @order_items.present? %>
    <div class="row">
      <!-- Basic Table -->
      <div class="col-lg-12">
        <%= link_to edit_setting_path(@order_items.last.order.id, redirect: 'sales'), id: "link_#{current_order.id}", remote: true, class: 'btn btn-default', style: "margin-left: 0; width: 100%;", data: { turbolinks: false } do %>
         <i class="" style="font-size: 18px;"><%=t(".setting")%></i>
        <% end %>
      </div>
      <div class="col-lg-12">
        <%= link_to send_to_order_path, class: "btn btn-primary", style: "width: 100%;", remote: true do %>
          <i class="" style="font-size: 18px;"><%=t(".send_to_order")%> (<%= "#{session[:order_count] if session[:order_count].present?}" %>)</i>
        <% end %>
      </div>
      <div class="col-sm-12">
        <div class="">
          <div class="table-responsive">
            <div id="" class="">
              <table class="table mb-30">
                <thead>
                  <tr role="row">
                    <th style="width: 246px;"><%=t(".product")%></th>
                    <th style="width: 406px;"><%=t(".quantity")%></th>
                    <th style="width: 116px;"><%=t(".price")%></th>
                    <th style="width: 155px;"><%=t(".actions")%></th>
                  </tr>
                </thead>
                <tbody>
                  <% @order_items.each do |order_item| %>
                    <tr role="row" class="odd">
                      <td class="txt-dark"><%= order_item.product.product_name %></td>
                      <td>
                        <%=order_item.quantity%>
                      </td>
                      <%= free?(order_item.unit_price) %>
                      <td>
                      <%= link_to edit_order_item_path(order_item), data: { turbolinks: false }, style: "margin-bottom: 5px;", class: "btn btn-primary" do %>
                        <i class="fa fa-pencil"></i>
                      <% end %>
                      <%= link_to sales_order_item_destroy_path(order_item), class: '', data: { turbolinks: false }, style: "margin-bottom: 5px;", method: :delete, remote: true, class: "btn btn-danger" do %>
                      <i class="fa fa-trash-o"></i>
                    <% end %>
                  </td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- /Basic Table -->
</div>
<div class="row">
  <div class="col-sm-12" style="margin-top: 20px; font-weight: bold;">
    <%if current_order.cash == 0%>
      <p>
        <label for="" class="lable-order"><%= t('.customer_receive_riel') %>:</label>
        <%= number_to_currency current_order.cash_in_riel , precision: 0%>
      </p>
    <%else%>
      <p>
        <label for="" class="lable-order"><%= t('.customer_receive_usd') %>:</label>
        <%= number_to_currency current_order.cash , precision: 2 %>
      </p>
    <%end%>

    <p >
      <label for="" class="lable-order"><%= t('.sub_total') %>:</label>
      <span id="sub_total">
        <%= number_to_currency @order_items.last.order.subtotal, precision: 2 %>
      </span>     
    </p>
    <p>
      <label for="" class="lable-order"><%= t('.discount') %>:</label>
      <span id="discount">
        <%= number_to_percentage @order_items.last.order.discount, precision: 0 %>
      </span>
    </p>

    <% if @order_items.last.order.total_cash_in_riel > 0 %>
      <p>
        <label for="" class="lable-order"><%= t('.change_in_dollar') %>:</label>       
        <span id="total_cash_in_riel">
          <%= number_to_currency ((@order_items.last.order.total_cash_in_riel / Constant::exchange_rate) - @order_items.last.order.total), precision: 2 %>
        </span>
      </p>
    <% end %>

    <%if @order_items.last.order.cash_in_riel == 0 && @order_items.last.order.cash == 0%>
      <p>
        <label for="" class="lable-order"><%= t('.change_in_riel') %>:</label>
        <span id="total_cash_in_riel_zero">
          ៛ <%= "#{0}"%>
        </span>
      </p>
    <%else%>
      <%if @order_items.last.order.cash_in_riel == 0%>
        <p>
          <label for="" class="lable-order"><%= t('.change_in_riel') %>:</label>
          <span id="change_riel">
           ៛<%= "#{(@order_items.last.order.total_cash_in_riel - (@order_items.last.order.total * Constant.exchange_rate)) / 4100 * 4000 }"%>
          </span>     
        </p>
        <%else@order_items.last.order.cash == 0%>
          <p>
            <label for="" class="lable-order"><%= t('.change_riel') %>:</label>
            <span id="change_riel">
             ៛<%= "#{(@order_items.last.order.total_cash_in_riel - (@order_items.last.order.total * Constant.exchange_rate)) }"%>
            </span>   
          </p>
        <%end%>
      <%end%>

      <p>
        <label for="" class="lable-order"><%= t('.grand_total_usd') %>:</label>
        <span id="grand_total">
          <%= number_to_currency @order_items.last.order.total %>
        </span>
      </p>

      <p>
        <label for="" class="lable-order"><%= t('.grand_total_riel') %>:</label>
        <span id="grand_total_riel">
          ៛<%= "#{@order_items.last.order.total * Constant.exchange_rate}"%>
        </span>
      </p>
      
    </div>
    <div class="col-lg-12" style="margin-top: 20px;">
      <%= link_to sale_path(@order_items.last.order), class: 'btn btn-success', style: "width: 100%;"  do%>
        <%=t('.checkout')%>
      <%end%>
    </div>
  </div>
<% end %>

app/views/sales/_product_row.html.erb
<div class="row">
  <% @products.each_slice(3) do |products| %>
    <% products.each do |product| %>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="margin-top: 20px;">
        <%= link_to sales_order_item_path(product_id: product.id, quantity: 1), remote: true do%>
          <div class="photo">
            <%if product.image.present?%>
              <img src="<%=product.image.url%>" class="img-responsive" alt="Product Image"/>
            <%else%>
               <img src="/no-product.png" class="img-responsive" alt="Product Image"/>
            <%end%>
          </div>
          <div class="info">
            <h6 style="font-size: 11px;"><%=product.product_name.capitalize%></h6>
            <span class="head-font block txt-orange-light-1 font-16">
              <%=number_to_currency(product.product_price)%>
            </span>
          </div>
        <%end%>       
      </div>
    <% end %>
  <% end %>
</div>

app/views/sales/index.html.erb
<!-- Main Content -->
<div id="send_to_order_succcess"></div>
<div id="update_order_succcess"></div>
<div id="update_quanity"></div>
<div class="page-wrapper">
  <div class="container-fluid pt-30">
    <div class="row">
      <div class="col-sm-4 col-md-7">
        <div class="panel panel-default border-panel card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark">Order</h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <div class="tab-struct custom-tab-1">
                <div class="order-item">
                  <%= render "order_item_row" if @order_items.present? %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-8 col-md-5">
        <div class="panel panel-default border-panel card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark">Products</h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <div class="tab-struct custom-tab-1 mt-40">
                <ul class="nav nav-tabs">
                  <%@categories.where.not(id: 1).each do |category|%>
                    <li>
                      <%= link_to category.category_name, product_path(category_id: category.id), class: "category", :remote => true %>
                    </li>
                  <%end%>
                </ul>

                <div class="tab-content" id="myTabContent_7">
                  <div class="product-list">
                    <%= render "product_row" if @products.present? %>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <%=render "applications/footer"%>

</div>

app/views/sales/order_item.js.erb
<%if session["order_id#{current_user.id}"].present?%>
  $(".order-item").html("<%= j render :partial => 'order_item_row', :locals => { :order_items => @order_items}%>");
<%else%>
  $("#send_to_order_succcess").html("<%= custom_flash_message%>");
  $(".session_order_count").html("Orders (<%= "#{ Order.where("is_paid=? AND order_status=? AND order_date=?", false, "order",DateTime.now.to_date).count}" %>)")
  $(".order-item").html("");
<%end%>

app/views/sales/product.js.erb
$(".product-list").html("<%= j render :partial => 'product_row', :locals => { :products => @products, order_item: @order_item}%>");

app/views/sales/show.html.erb
<!-- Main Content -->
<div class="page-wrapper">
  <div class="container">
    <!-- Row -->
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default border-panel card-view">
          <div class="panel-heading">
            <div class="pull-left">
              <h6 class="panel-title txt-dark">Invoice</h6>
            </div>
            <div class="pull-right">
              <h6 class="txt-dark">Order #000<%=@order.id%></h6>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="panel-wrapper collapse in">
            <div class="panel-body">
              <div class="row">
                <div class="col-xs-6">
                  <span class="txt-dark head-font inline-block capitalize-font mb-5">Billed to:</span>
                  <address class="mb-15">
                    <span class="address-head mb-5">Kompot Restuanrent</span>
                    795 Folsom Ave, Suite 600
                    <br>
                    San Francisco, CA 94107
                    <br>
                    <abbr title="Phone">P:</abbr>(133) 456-7890
                  </address>
                </div>
                <div class="col-xs-6 text-right">
                  <span class="txt-dark head-font inline-block capitalize-font mb-5">shiped to:</span>
                  <address class="mb-15">
                    <span class="address-head mb-5">Xyz, Inc.</span>
                    795 Folsom Ave, Suite 600
                    <br>
                    San Francisco, CA 94107
                    <br>
                    <abbr title="Phone">P:</abbr>(123) 456-7890
                  </address>
                </div>
              </div>

              <div class="row">
                <div class="col-xs-6">
                </div>
                <div class="col-xs-6 text-right">
                  <address>
                    <span class="txt-dark head-font capitalize-font mb-5">order date:</span><br>
                    <%=@order.order_date%><br><br>
                  </address>
                </div>
              </div>

              <div class="seprator-block"></div>

              <div class="invoice-bill-table">
                <div class="table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Totals</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%@order.order_items.each do |item|%>
                        <tr>
                          <td><%=item.product.product_name.capitalize%></td>
                          <td><%=number_to_currency(item.product.product_price)%></td>
                          <td><%=item.quantity%></td>
                          <td><%=number_to_currency(item.total_price)%></td>
                        </tr>
                      <%end%>
                      <tr class="txt-dark">
                        <td></td>
                        <td></td>
                        <td>Total</td>
                        <td><%=number_to_currency(@order.total)%></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="button-list pull-right">
                  <%=link_to "Cancel", sales_path, class: "btn btn-orange mr-10", id: "cancel"%>
                  <button type="button" class="btn btn-default btn-outline btn-icon left-icon" onclick="javascript:window.print();">
                    <i class="fa fa-print"></i>
                    <span>
                      Print</span>
                  </button>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Row -->
    <%=render "applications/footer"%>
  </div>

app/views/sales/test.html.erb
<div class="table-responsive">
  <table class="table mb-0">
    <thead>
      <tr>
        <th>Qty</th>
        <th>Product Name</th>
        <th>Price</th>
        <th>Discount</th>
        <th>Total Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.quantity %>x</td>
        <td><%= order_item.product.product_name %></td>
        <td><%= number_to_currency order_item.unit_price, precision: 2 %></td>
        <td><%= "- #{number_to_percentage order_item.discount, precision: 2}" %></td>
        <td>
          <%= number_to_currency order_item.total_price, precision: 2 %>
        </td>
        <td>
          <%= link_to edit_order_item_path(order_item), data: { turbolinks: false } do %>
            <i class="fa fa-pencil"></i>
            <% end %>
          <%= link_to sales_order_item_destroy_path(order_item), class: '', data: { turbolinks: false }, method: :delete, remote: true do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-sm-12" style="margin-top:40px;">
    <%if @order_items.last.order.cash == 0%>
      <p>
        <label for="" class="lable-order"><%= t('.Customer Riel Cast') %>:
        </label>
        <%= number_to_currency @order_items.last.order.cash_in_riel , precision: 2 %>
      </p>
    <%else%>
      <p>
        <label for="" class="lable-order"><%= t('.Customer Riel Cast') %>:
        </label>
        <%= number_to_currency @order_items.last.order.cash , precision: 2 %>
      </p>
    <%end%>
    <p>
      <label for="" class="lable-order"><%= t('.subtotal') %>:
      </label>
      <%= number_to_currency @order_items.last.order.subtotal, precision: 2 %>
    </p>

    <p>
      <label for="" class="lable-order"><%= t('.tax') %>:
      </label>
      <%= number_to_currency @order_items.last.order.tax, precision: 2 %>
    </p>

    <p>
      <label for="" class="lable-order"><%= t('.shipping') %>:
      </label>
      <%= number_to_currency @order_items.last.order.shipping, precision: 2 %>
    </p>

    <p>
      <label for="" class="lable-order"><%= t('.discount') %>:
      </label>
      <%= number_to_percentage @order_items.last.order.discount, precision: 2 %>
    </p>

    <% if @order_items.last.order.total_cash_in_riel > 0 %>
      <p>
        <label for="" class="lable-order">
          <%= t('.change_dollar') %>:
        </label>
        <%= number_to_currency ((@order_items.last.order.total_cash_in_riel / Constant::exchange_rate) - @order_items.last.order.total), precision: 2 %>
      </p>
    <% end %>

    <%if @order_items.last.order.cash_in_riel == 0 && @order_items.last.order.cash == 0%>
      <p>
        <label for="" class="lable-order"><%= t('.change_riel') %>:
        </label>
        <%= "#{0}"%>
      </p>
    <%else%>
      <%if @order_items.last.order.cash_in_riel == 0%>
        <p>
          <label for="" class="lable-order"><%= t('.change_riel') %>:
          </label>
          <%= "#{(@order_items.last.order.total_cash_in_riel - (@order_items.last.order.total * Constant.exchange_rate)) / 4100 * 4000 }"%>
        </p>
        <%else@order_items.last.order.cash == 0%>
          <p>
            <label for="" class="lable-order"><%= t('.change_riel') %>:
            </label>
            <%= "#{(@order_items.last.order.total_cash_in_riel - (@order_items.last.order.total * Constant.exchange_rate)) }"%>
          </p>
        <%end%>
      <%end%>

      <p>
        <label for="" class="lable-order">
          <%= t('.grand_total') %>:
        </label>
        <%= number_to_currency @order_items.last.order.total, precision: 1 %>
      </p>

      <p>
        <label for="" class="lable-order"><%= t('.grand_total_riel') %>:
        </label>
        <%= "#{@order_items.last.order.total * Constant.exchange_rate}"%>
      </p>
      <div style="margin-top: 20px;">
        <%= link_to edit_order_path(@order_items.last.order.id, redirect: 'sales'), class: 'btn btn-default', data: { turbolinks: false } do %>
        <i class="">settings</i>
      <% end %>

      <%= link_to "checkout", sale_path(@order_items.last.order), class: 'btn btn-default' %>

      <%= link_to fast_cash_index_path(order_id: @order_items.last.order.id, redirect: 'sales'), class: 'btn btn-default', data: { turbolinks: false } do %>
      <i class="material-icons white-text text-darken-4">Fast Cash</i>
    <% end %>
  </div>
</div>
</div>